// src/domain/constants/quotes.ts
export type QuoteItem = {
  text: string;
  author?: string;
  tags?: string[];
};

export const QUOTES: QuoteItem[] = [
  { text: "기록은 기억을 돕는 가장 정직한 방법이다.", author: "Log-in Diary", tags: ["기록", "본질"] },
  { text: "작게 시작하면, 꾸준함이 이긴다.", author: "Log-in Diary", tags: ["시작", "성실"] },
  { text: "감정은 파도가 아니라 신호다.", author: "Log-in Diary", tags: ["감정", "위로"] },
  { text: "완벽보다 지속.", author: "Log-in Diary", tags: ["태도", "성장"] },
  { text: "어제의 후회보다 내일의 설렘을 적자.", author: "Log-in Diary", tags: ["긍정", "미래"] },
  { text: "생각은 글로 적힐 때 비로소 정리가 된다.", author: "앤 패디먼", tags: ["기록", "사고"] },
  { text: "가장 어두운 밤도 결국 아침에 자리를 내준다.", author: "빅토르 위고", tags: ["위로", "희망"] },
  { text: "남과 비교하지 말고, 어제의 자신과 비교하라.", author: "조던 피터슨", tags: ["자존감", "성장"] },
  { text: "휴식은 게으름이 아니라, 다음을 위한 전략이다.", author: "Log-in Diary", tags: ["휴식", "효율"] },
  { text: "오늘의 사소한 행복이 내일의 버팀목이 된다.", author: "Log-in Diary", tags: ["행복", "일상"] },
  { text: "실수는 배움의 다른 이름일 뿐이다.", author: "Log-in Diary", tags: ["성장", "도전"] },
  { text: "천천히 가는 것을 두려워 말고, 멈추는 것을 두려워하라.", author: "중국 격언", tags: ["끈기", "노력"] },
  { text: "내일의 나는 오늘의 내가 만든 기록 위에 서 있다.", author: "Log-in Diary", tags: ["기록", "정체성"] },
  { text: "감정을 글로 옮기면, 감정의 주인이 될 수 있다.", author: "Log-in Diary", tags: ["감정", "통제"] },
  { text: "모든 꽃이 봄의 첫날에 피지는 않는다.", author: "Log-in Diary", tags: ["위로", "인내"] },
  { text: "작은 습관이 모여 운명을 만든다.", author: "윌리엄 제임스", tags: ["습관", "변화"] },
  { text: "오늘 하루도 수고한 당신에게 정직한 쉼을.", author: "Log-in Diary", tags: ["위로", "마무리"] },
  { text: "성공은 최종적인 것이 아니며, 실패는 치명적인 것이 아니다.", author: "윈스턴 처칠", tags: ["용기", "회복탄력성"] },
  { text: "가장 위대한 영광은 한 번도 넘어지지 않는 것이 아니라, 넘어질 때마다 일어나는 데 있다.", author: "공자", tags: ["태도", "인내"] },
  { text: "당신의 가치는 타인의 시선이 결정하지 않는다.", author: "Log-in Diary", tags: ["자존감", "중심"] },
  { text: "오늘의 할 일을 다 못했어도 당신의 가치는 변하지 않는다.", author: "Log-in Diary", tags: ["위로", "자존감"] },
  { text: "기회는 준비된 자에게만 찾아온다.", author: "루이 파스퇴르", tags: ["준비", "기회"] },
  { text: "충분히 잘하고 있다. 다만 속도가 다를 뿐이다.", author: "Log-in Diary", tags: ["위로", "격려"] },
  { text: "단순함이 궁극의 정교함이다.", author: "레오나르도 다 빈치", tags: ["본질", "단순화"] },
  { text: "삶을 기록하는 것은 삶을 두 번 사는 것이다.", author: "아나이스 닌", tags: ["기록", "가치"] },
  { text: "현재에 집중하라. 과거는 지나갔고 미래는 알 수 없다.", author: "Log-in Diary", tags: ["현재", "집중"] },
  { text: "불안은 미래를 미리 빌려와서 겪는 고통이다.", author: "Log-in Diary", tags: ["감정", "심리"] },
  { text: "목표는 구체적으로, 계획은 유연하게.", author: "Log-in Diary", tags: ["전략", "유연함"] },
  { text: "남들의 속도가 아니라 당신의 방향이 중요하다.", author: "Log-in Diary", tags: ["방향", "소신"] },
  { text: "행동은 말보다 더 크게 울린다.", author: "Log-in Diary", tags: ["실행", "신뢰"] },
  { text: "지루한 반복이 비범함을 만든다.", author: "Log-in Diary", tags: ["노력", "성공"] },
  { text: "스스로를 믿는 것이 성공의 첫 번째 비결이다.", author: "랄프 왈도 에머슨", tags: ["자신감", "신뢰"] },
  { text: "포기하고 싶을 때, 왜 시작했는지를 생각하라.", author: "Log-in Diary", tags: ["초심", "의지"] },
  { text: "가장 좋은 복수는 보란 듯이 성공하는 것이다.", author: "프랭크 시나트라", tags: ["동기부여", "성공"] },
  { text: "어제보다 나은 오늘이면 충분하다.", author: "Log-in Diary", tags: ["성장", "만족"] },
  { text: "당신의 생각은 당신의 인생이 된다.", author: "마르쿠스 아우렐리우스", tags: ["철학", "사고"] },
  { text: "행운은 용기를 내는 사람의 편이다.", author: "버질", tags: ["용기", "행운"] },
  { text: "지금 하고 있는 고민은 1년 뒤면 기억도 안 날 일이다.", author: "Log-in Diary", tags: ["관점", "위로"] },
  { text: "비우지 않으면 채울 수 없다.", author: "Log-in Diary", tags: ["미니멀리즘", "비움"] },
  { text: "기록되지 않은 것은 존재하지 않는 것과 같다.", author: "Log-in Diary", tags: ["기록", "존재"] },
  { text: "자신을 사랑하는 것이 평생 로맨스의 시작이다.", author: "오스카 와일드", tags: ["사랑", "자신"] },
  { text: "작은 것에 감사할 줄 알 때 큰 기쁨이 찾아온다.", author: "Log-in Diary", tags: ["감사", "행복"] },
  { text: "어려움 속에 기회가 있다.", author: "알베르트 아인슈타인", tags: ["기회", "역경"] },
  { text: "계획 없는 목표는 단지 희망사항일 뿐이다.", author: "생텍쥐페리", tags: ["계획", "실행"] },
  { text: "당신이 할 수 있다고 믿든 할 수 없다고 믿든, 당신이 옳다.", author: "헨리 포드", tags: ["믿음", "태도"] },
  { text: "인생은 속도가 아니라 방향이다.", author: "괴테", tags: ["방향", "인생"] },
  { text: "실패한 것이 아니라, 안 되는 방법 1만 가지를 찾은 것이다.", author: "토마스 에디슨", tags: ["관점", "끈기"] },
  { text: "진정한 발견은 새로운 땅을 찾는 것이 아니라 새로운 눈을 갖는 것이다.", author: "마르셀 프루스트", tags: ["통찰", "변화"] },
  { text: "가장 큰 위험은 아무런 위험도 감수하지 않는 것이다.", author: "마크 저커버그", tags: ["도전", "리스크"] },
  { text: "오늘 하루 당신의 이야기는 당신만이 쓸 수 있다.", author: "Log-in Diary", tags: ["주체성", "기록"] }
];